dist: trusty
sudo: required
language: node_js
node_js:
  - '14'
branches:
  only:
    - master
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --code-coverage
  - npm run build
after_success:
  - npm run codacy
# deploy:
#   provider: heroku
#   app: decide-angular
#   strategy: git
#   api_key:
#     secure: jw0gR6wPAwVA4nsQZBB+9UwNDlirP/fUiTGbr3FzBIkqk02+RhFFoyniexdj0+MQ9y4FKG5JmMzVMrsEKnknnzdkSKQLq3pzWZZt5d1ZnLbOr15AMZcfvWoJH496jQCSL5i0eSPlNdHhIf5ZvPWZ6ERLfayA4hCdL5Ti0qsEjpMv+gv5I5EWmAjLJhOyRyCRhMtuF3EV9AWayiUY4wFVAXb/uvfJEho5VyJg9WPfwXBiNyLkuXiEWvtSZwv2oYKV5p2jUx21SNxYIqDf/NEpl3WHYRihadSw+MLJvE2kGe6gUVhhG1UGD5OZEvUAbyn+nmmTt7ep1XDsjgLD4IHIo2pIjyCCRUXe3HX9IICbgxiph8GtrVCmJih+fCFd0dU0YJk1jW8dzsP4cwr+LwdswuI7A8YfnTnW57JxbxVgYc82zHhWCCkVvqyXDGxSICqnOcyB0uJ3oC7XMH8/lKtLqMVxBtM22jwfnfcmKfmaQTs5gv2CAzRW43Kr64JrD0FoKvnKTZo2jo4pXpRgNtbMtonuyR5WuRbsaQYLPkRS4YjYa1IiYdD5YDQSPHXYC2rS71Nb17i+urkFpWKTaPYZDmYsp9mWXMIdvepzDOd1j/l9HHYOPufF9bN6izkqYRwqi9GxqvdRK2X17GbvOpvB7zweRVcbUVOOiOXSZhnRtow=
