version: '3.0'

# Define the services/ containers to be run
services:
  frontend: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - '4200:4200' # specify port mapping

  backend: # name of the second service
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend # specify the directory of the Dockerfile
    environment:
      - DB_HOSTNAME=database
    ports:
      - '3000:3000' #specify ports mapping
    depends_on:
      - database
    links:
      - database # link this service to the database service

  populate: # name of the second service
    build:
      context: ./backend
      dockerfile: ./Dockerfile.populate # specify the directory of the Dockerfile
    environment:
      - DB_HOSTNAME=database
    depends_on:
      - database
      - backend
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - '27017:27017' # specify port forwarding
