FROM node:14
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app
RUN npm install
COPY . /usr/src/app
RUN npm install -g mongoose@5.13.12
RUN npm install -g mongoose-data-seed@2.1.6
EXPOSE 3000
CMD ["npm","start"]