name: GitHub Actions
on: [push]
jobs:
  Run tests with coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/setup-node@v2
        name: Setup node version
        with:
          node-version: '14'
      - name: Build project and run tests
        working-directory: ./frontend
        run: |
          npm install
          npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --code-coverage
          npm run build

  Check job status:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🍏 This job's status is ${{ job.status }}."
